const PRIMARY = '#FFFFFF';
const PRIMARY_TRANSLUCENT = 'rgba(255,255,255,0.08)';
const SECONDARY_TRANSLUCENT = 'rgba(255,255,255,0.3)';
const SECONDARY = '#F9F9F9';
const ERROR = '#FF0000';

export default {
    PRIMARY,
    PRIMARY_TRANSLUCENT,
    SECONDARY_TRANSLUCENT,
    SECONDARY,
    ERROR,
};
